services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meu_app_development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               until pg_isready -h db -p 5432; do
                 echo 'Waiting for Postgres...'; sleep 1;
               done;
               bundle exec rails s -b 0.0.0.0"
    volumes:
      - "./meu_app:/meu_app"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data: